name: Update Leaderboard

on:
  push:
    paths:
      - "static/grading/results/*"

jobs:
  aggregate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run aggregator script
      run: python3 scripts/aggregator.py

    - name: Commit updated leaderboard
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add static/json/leaderboard.json
        git commit -m "Update leaderboard"
        git push